#!/usr/bin/env python3
"""Build the compact OSRM-grid sensitivity table for the TR-B draft."""

from __future__ import annotations

from pathlib import Path

import pandas as pd

RESULT_DIR = Path("results/path3_osrm_grid_selected")
OUT_TEX = Path("paper/path3_osrm_sensitivity.tex")
OUT_MD = Path("docs/path3-osrm-sensitivity.md")


def _fmt(x: float, digits: int = 1) -> str:
    return f"{float(x):.{digits}f}"


def main() -> None:
    summary = pd.read_csv(RESULT_DIR / "external_baselines_summary.csv")
    order = [
        ("batch_replay", "Batch replay"),
        ("share_lp_hand_tuned", "Share-target LP"),
        ("spatial_gate_robust_cvar", "Calibrated DCR"),
    ]
    lookup = summary.set_index("method")
    rows = []
    md_rows = []
    for method, label in order:
        r = lookup.loc[method]
        improvement = (
            "--"
            if pd.isna(r.get("improvement_vs_replay_pct"))
            else _fmt(r["improvement_vs_replay_pct"], 1)
        )
        rows.append(
            f"{label} & {_fmt(r['mean_wait_s'], 1)} & "
            f"{_fmt(r['reposition_dist_m_per_trip'], 1)} & "
            f"{_fmt(r['zone_wait_p90_p10_gap_s'], 1)} & "
            f"{_fmt(r['zone_wait_gini'], 3)} & {improvement} \\\\"
        )
        md_rows.append(
            f"| {label} | {_fmt(r['mean_wait_s'], 1)} | "
            f"{_fmt(r['reposition_dist_m_per_trip'], 1)} | "
            f"{_fmt(r['zone_wait_p90_p10_gap_s'], 1)} | "
            f"{_fmt(r['zone_wait_gini'], 3)} | {improvement} |"
        )

    tex = (
        "% Auto-generated by scripts/analyze_path3_osrm_sensitivity.py\n\n"
        "\\begin{table}[t]\n"
        "\\centering\n"
        "\\caption{Cached-grid OSRM routing sensitivity on two representative "
        "scenarios and three seeds. Road-network travel times increase absolute "
        "waits, but calibrated DCR remains on the movement-efficient frontier.}\n"
        "\\label{tab:path3-osrm-sensitivity}\n"
        "\\small\n"
        "\\setlength{\\tabcolsep}{4pt}\n"
        "\\resizebox{\\linewidth}{!}{%\n"
        "\\begin{tabular}{lrrrrr}\n"
        "\\toprule\n"
        "Method & Wait (s) & Repos. m/trip & Zone gap (s) & Zone Gini & "
        "Improv. \\% \\\\\n"
        "\\midrule\n"
        + "\n".join(rows)
        + "\n\\bottomrule\n"
        "\\end{tabular}%\n"
        "}\n"
        "\\end{table}\n"
    )
    OUT_TEX.write_text(tex)

    lines = [
        "# Path 3 OSRM Sensitivity",
        "",
        "Cached-grid OSRM sensitivity over `jan_weekday_am` and "
        "`jun_late_night`, three seeds each.",
        "",
        "| Method | Wait | Repos. m/trip | Zone gap | Zone Gini | Improv. % |",
        "|---|---:|---:|---:|---:|---:|",
        *md_rows,
        "",
        "Interpretation: road-network routing increases absolute waits relative to "
        "Haversine. Calibrated DCR remains slightly faster than share-target LP "
        "on this two-scenario OSRM sample and uses 11.8% less empty movement "
        "than share-target LP, while its zone-gap/Gini are not better in this "
        "small sensitivity.",
    ]
    OUT_MD.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT_TEX}")
    print(f"Wrote {OUT_MD}")


if __name__ == "__main__":
    main()
