#!/usr/bin/env python3
"""Build DCR frontier diagnostics for the TR-B rebuild."""

from __future__ import annotations

from pathlib import Path

import pandas as pd

WEIGHTED_FRONTIER = Path("results/path3_spatial_robust_frontier.csv")
BUDGET_FRONTIER = Path("results/path3_spatial_robust_budget_frontier.csv")
CALIBRATED_BUDGET_FRONTIER = Path(
    "results/path3_constrained_dcr_buffer70_sweep/constrained_dcr_sweep_summary.csv"
)
SELECTED_10SEED = Path("results/path3_buffer70_m4_10seed/external_baselines_summary.csv")
INSTRUMENTATION_SMOKE = Path(
    "results/path3_constrained_instrumentation_smoke/external_baselines.csv"
)
OUT_DIR = Path("results/path3_dcr_frontier_analysis")
OUT_TEX = Path("paper/path3_frontier_diagnostics.tex")
OUT_MD = Path("docs/path3-dcr-frontier-analysis.md")


def _fmt(x: float, digits: int = 1) -> str:
    return f"{float(x):.{digits}f}"


def _load_frontiers() -> pd.DataFrame:
    weighted = pd.read_csv(WEIGHTED_FRONTIER)
    weighted = weighted.rename(columns={"move_mult": "setting"})
    weighted["family"] = "Weighted DCR"
    weighted["setting_label"] = weighted["setting"].map(lambda x: f"m={x:g}")

    budget_path = (
        CALIBRATED_BUDGET_FRONTIER
        if CALIBRATED_BUDGET_FRONTIER.exists()
        else BUDGET_FRONTIER
    )
    budget = pd.read_csv(budget_path)
    budget = budget.rename(columns={"shortage_reduction": "setting"})
    budget["family"] = "Constrained DCR"
    budget["setting_label"] = budget["setting"].map(lambda x: f"red.={x:g}")

    cols = [
        "family",
        "setting_label",
        "setting",
        "mean_wait_s",
        "reposition_dist_m_per_trip",
        "zone_wait_gini",
        "zone_wait_p90_p10_gap_s",
        "lp_solve_time_p95_ms",
    ]
    return pd.concat([weighted[cols], budget[cols]], ignore_index=True)


def _efficient_points(df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for idx, row in df.iterrows():
        dominates = (
            (df["mean_wait_s"] <= row["mean_wait_s"])
            & (df["reposition_dist_m_per_trip"] <= row["reposition_dist_m_per_trip"])
            & (
                (df["mean_wait_s"] < row["mean_wait_s"])
                | (df["reposition_dist_m_per_trip"] < row["reposition_dist_m_per_trip"])
            )
        )
        rows.append(not bool(dominates.any()))
    out = df.copy()
    out["is_wait_reposition_efficient"] = rows
    return out


def _selected_summary() -> tuple[pd.Series, pd.Series, pd.Series]:
    summary = pd.read_csv(SELECTED_10SEED).set_index("method")
    return (
        summary.loc["spatial_gate_robust_cvar"],
        summary.loc["share_lp_hand_tuned"],
        summary.loc["scenario_chance_mpc"],
    )


def _write_tex(frontier: pd.DataFrame) -> None:
    rows = []
    display = frontier.sort_values(["family", "mean_wait_s"]).copy()
    for _, row in display.iterrows():
        marker = "$\\star$" if row["is_wait_reposition_efficient"] else ""
        rows.append(
            f"{row['family']} & {row['setting_label']} & "
            f"{_fmt(row['mean_wait_s'], 1)} & "
            f"{_fmt(row['reposition_dist_m_per_trip'], 1)} & "
            f"{_fmt(row['zone_wait_p90_p10_gap_s'], 1)} & "
            f"{_fmt(row['zone_wait_gini'], 3)} & {marker} \\\\"
        )

    tex = (
        "% Auto-generated by scripts/analyze_path3_dcr_frontier.py\n\n"
        "\\begin{table}[t]\n"
        "\\centering\n"
        "\\caption{DCR movement/wait frontier diagnostics. Stars mark non-dominated "
        "points in mean wait and empty repositioning among the displayed settings.}\n"
        "\\label{tab:path3-dcr-frontier}\n"
        "\\small\n"
        "\\setlength{\\tabcolsep}{4pt}\n"
        "\\resizebox{\\linewidth}{!}{%\n"
        "\\begin{tabular}{llrrrrc}\n"
        "\\toprule\n"
        "Family & Setting & Wait (s) & Repos. m/trip & Zone gap (s) & "
        "Zone Gini & Eff. \\\\\n"
        "\\midrule\n"
        + "\n".join(rows)
        + "\n\\bottomrule\n"
        "\\end{tabular}\n"
        "}\n"
        "\\end{table}\n"
    )
    OUT_TEX.write_text(tex)


def _write_markdown(frontier: pd.DataFrame) -> None:
    selected, share, chance = _selected_summary()
    constrained = frontier[frontier["family"] == "Constrained DCR"].copy()
    best_budget_wait = constrained.loc[constrained["mean_wait_s"].idxmin()]
    low_move_budget = constrained.loc[constrained["reposition_dist_m_per_trip"].idxmin()]
    selected_wait = float(selected["mean_wait_s"])
    selected_repos = float(selected["reposition_dist_m_per_trip"])

    instr_text = "Not available."
    if INSTRUMENTATION_SMOKE.exists():
        smoke = pd.read_csv(INSTRUMENTATION_SMOKE).iloc[0]
        instr_text = (
            f"one-scenario smoke: wait {_fmt(smoke['mean_wait_s'], 1)}s, "
            f"repos {_fmt(smoke['reposition_dist_m_per_trip'], 1)}m/trip, "
            f"statuses `{smoke.get('solve_status_counts_json', '{}')}`, "
            f"baseline CVaR mean {_fmt(smoke.get('dcr_baseline_cvar_mean', 0.0), 1)}, "
            f"budget mean {_fmt(smoke.get('dcr_cvar_budget_mean', 0.0), 1)}."
        )

    promote = (
        float(best_budget_wait["mean_wait_s"]) <= selected_wait + 1.5
        and float(best_budget_wait["reposition_dist_m_per_trip"]) < selected_repos
    )
    verdict = (
        "Constrained DCR is strong enough to consider as the headline controller."
        if promote
        else (
            "Do not promote constrained DCR as the headline yet; keep weighted "
            "DCR as the implemented frontier and constrained DCR as the "
            "theorem-clean formulation."
        )
    )

    lines = [
        "# DCR Frontier Analysis",
        "",
        "Generated by `scripts/analyze_path3_dcr_frontier.py`.",
        "",
        "## Headline 10-seed comparison",
        "",
        f"- Selected weighted/calibrated DCR: {_fmt(selected_wait, 1)}s wait, "
        f"{_fmt(selected_repos, 1)}m/trip repositioning.",
        f"- Share-target LP: {_fmt(share['mean_wait_s'], 1)}s wait, "
        f"{_fmt(share['reposition_dist_m_per_trip'], 1)}m/trip.",
        f"- Scenario chance-MPC: {_fmt(chance['mean_wait_s'], 1)}s wait, "
        f"{_fmt(chance['reposition_dist_m_per_trip'], 1)}m/trip.",
        "",
        "## Constrained-DCR status",
        "",
        f"- Best constrained wait point: {best_budget_wait['setting_label']}, "
        f"{_fmt(best_budget_wait['mean_wait_s'], 1)}s wait, "
        f"{_fmt(best_budget_wait['reposition_dist_m_per_trip'], 1)}m/trip.",
        f"- Lowest constrained movement point: {low_move_budget['setting_label']}, "
        f"{_fmt(low_move_budget['mean_wait_s'], 1)}s wait, "
        f"{_fmt(low_move_budget['reposition_dist_m_per_trip'], 1)}m/trip.",
        f"- Instrumentation: {instr_text}",
        "",
        "## Verdict",
        "",
        verdict,
        "",
        "## Frontier table",
        "",
        "| Family | Setting | Wait | Repos. m/trip | Zone gap | Zone Gini | Efficient |",
        "|---|---:|---:|---:|---:|---:|:---:|",
    ]
    for _, row in frontier.sort_values(["family", "mean_wait_s"]).iterrows():
        lines.append(
            f"| {row['family']} | {row['setting_label']} | "
            f"{_fmt(row['mean_wait_s'], 1)} | "
            f"{_fmt(row['reposition_dist_m_per_trip'], 1)} | "
            f"{_fmt(row['zone_wait_p90_p10_gap_s'], 1)} | "
            f"{_fmt(row['zone_wait_gini'], 3)} | "
            f"{'yes' if row['is_wait_reposition_efficient'] else 'no'} |"
        )
    OUT_MD.write_text("\n".join(lines) + "\n")


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    frontier = _efficient_points(_load_frontiers())
    frontier.to_csv(OUT_DIR / "frontier_summary.csv", index=False)
    _write_tex(frontier)
    _write_markdown(frontier)
    print(f"Wrote {OUT_DIR / 'frontier_summary.csv'}")
    print(f"Wrote {OUT_TEX}")
    print(f"Wrote {OUT_MD}")


if __name__ == "__main__":
    main()
