#!/usr/bin/env python3
"""Quantify the operational value of Path 3 empty-movement reductions."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

METHOD_LABELS = {
    "share_lp_hand_tuned": "Share-target LP",
    "scenario_chance_mpc": "Scenario chance-MPC",
}
DCR_METHOD = "spatial_gate_robust_cvar"


def _fmt(value: float, digits: int = 1) -> str:
    return f"{float(value):.{digits}f}"


def _money(value: float) -> str:
    return f"\\${float(value):,.0f}"


def build_table(
    results_csv: Path,
    out_csv: Path,
    out_tex: Path,
    unit_cost_per_km: float,
    low_cost_per_km: float,
    high_cost_per_km: float,
) -> pd.DataFrame:
    df = pd.read_csv(results_csv)
    dcr = df[df["method"] == DCR_METHOD].copy()
    if dcr.empty:
        raise ValueError(f"Missing DCR method {DCR_METHOD} in {results_csv}")

    rows = []
    for method, label in METHOD_LABELS.items():
        base = df[df["method"] == method].copy()
        if base.empty:
            raise ValueError(f"Missing baseline method {method} in {results_csv}")
        merged = base.merge(
            dcr,
            on=["scenario", "seed"],
            suffixes=("_baseline", "_dcr"),
            validate="one_to_one",
        )
        base_m = (
            merged["reposition_dist_m_per_trip_baseline"]
            * merged["completed_trips_baseline"]
        )
        dcr_m = (
            merged["reposition_dist_m_per_trip_dcr"]
            * merged["completed_trips_dcr"]
        )
        total_saved_km = float((base_m - dcr_m).sum() / 1000.0)
        completed_trips = float(merged["completed_trips_dcr"].sum())
        saved_m_per_trip = float((total_saved_km * 1000.0) / completed_trips)
        saved_km_per_million = saved_m_per_trip * 1000.0
        base_repos = float(merged["reposition_dist_m_per_trip_baseline"].mean())
        dcr_repos = float(merged["reposition_dist_m_per_trip_dcr"].mean())
        reduction_pct = 100.0 * (base_repos - dcr_repos) / base_repos
        wait_delta = float((merged["mean_wait_s_dcr"] - merged["mean_wait_s_baseline"]).mean())
        completion_delta_pp = 100.0 * float(
            (merged["completion_rate_dcr"] - merged["completion_rate_baseline"]).mean()
        )
        rows.append(
            {
                "baseline": label,
                "matched_runs": int(len(merged)),
                "wait_delta_s": wait_delta,
                "completion_delta_pp": completion_delta_pp,
                "saved_m_per_trip": saved_m_per_trip,
                "reduction_pct": reduction_pct,
                "sample_saved_km": total_saved_km,
                "completed_trips": completed_trips,
                "saved_km_per_million_trips": saved_km_per_million,
                "value_per_million_at_unit_cost": saved_km_per_million * unit_cost_per_km,
                "value_per_million_low": saved_km_per_million * low_cost_per_km,
                "value_per_million_high": saved_km_per_million * high_cost_per_km,
            }
        )

    summary = pd.DataFrame(rows)
    out_csv.parent.mkdir(parents=True, exist_ok=True)
    out_tex.parent.mkdir(parents=True, exist_ok=True)
    summary.to_csv(out_csv, index=False)

    body = []
    for _, row in summary.iterrows():
        body.append(
            f"{row['baseline']} & {_fmt(row['wait_delta_s'], 2)} & "
            f"{_fmt(row['saved_m_per_trip'], 1)} & "
            f"{_fmt(row['reduction_pct'], 1)} & "
            f"{_fmt(row['saved_km_per_million_trips'], 0)} & "
            f"{_money(row['value_per_million_low'])}--"
            f"{_money(row['value_per_million_high'])} \\\\"
        )

    tex = (
        "% Auto-generated by scripts/analyze_path3_operational_value.py\n\n"
        "\\begin{table}[t]\n"
        "\\centering\n"
        "\\caption{Operational value of calibrated DCR's empty-movement reduction "
        "relative to the two strongest non-oracle wait baselines. "
        "The dollar column is an illustrative sensitivity range using "
        f"\\${low_cost_per_km:.2f}--\\${high_cost_per_km:.2f}/km of empty "
        "repositioning; it is not used by the controller.}\n"
        "\\label{tab:path3-operational-value}\n"
        "\\small\n"
        "\\setlength{\\tabcolsep}{3pt}\n"
        "\\resizebox{\\linewidth}{!}{%\n"
        "\\begin{tabular}{@{}lrrrrr@{}}\n"
        "\\toprule\n"
        "Comparator & Wait penalty (s) & Saved m/trip & Saved \\% & "
        "Saved km / $10^6$ trips & Value range / $10^6$ trips \\\\\n"
        "\\midrule\n"
        + "\n".join(body)
        + "\n\\bottomrule\n"
        "\\end{tabular}%\n"
        "}\n"
        "\\end{table}\n"
    )
    out_tex.write_text(tex)
    return summary


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--results-csv",
        type=Path,
        default=Path("results/path3_buffer70_m4_10seed/external_baselines.csv"),
    )
    parser.add_argument(
        "--out-csv",
        type=Path,
        default=Path("results/path3_operational_value/operational_value.csv"),
    )
    parser.add_argument(
        "--out-tex",
        type=Path,
        default=Path("paper/path3_operational_value.tex"),
    )
    parser.add_argument("--unit-cost-per-km", type=float, default=0.50)
    parser.add_argument("--low-cost-per-km", type=float, default=0.25)
    parser.add_argument("--high-cost-per-km", type=float, default=1.00)
    args = parser.parse_args()

    summary = build_table(
        args.results_csv,
        args.out_csv,
        args.out_tex,
        args.unit_cost_per_km,
        args.low_cost_per_km,
        args.high_cost_per_km,
    )
    print(summary.to_string(index=False))
    print(f"\nWrote {args.out_csv}")
    print(f"Wrote {args.out_tex}")


if __name__ == "__main__":
    main()
