#!/usr/bin/env python3
"""Summarize DCR mixture-dominance diagnostics for the TR-B manuscript."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


def _fmt(value: float, digits: int = 1) -> str:
    return f"{float(value):.{digits}f}"


def build_table(results_csv: Path, out_csv: Path, out_tex: Path) -> pd.DataFrame:
    df = pd.read_csv(results_csv)
    required = {
        "dcr_dominance_n",
        "dcr_dominance_hold_rate",
        "dcr_dominance_delta_mean",
        "dcr_dominance_delta_p95",
        "dcr_dominance_delta_max",
        "dcr_mixture_shortage_mean",
        "dcr_shortage_term_mean",
    }
    missing = sorted(required.difference(df.columns))
    if missing:
        raise ValueError(f"Missing dominance columns in {results_csv}: {missing}")

    no_idle = df.get("solve_status_no_idle_supply", pd.Series(0, index=df.index))
    zero_budget = df.get("solve_status_zero_move_budget", pd.Series(0, index=df.index))
    no_route = df.get(
        "solve_status_no_source_or_destination_zones",
        pd.Series(0, index=df.index),
    )

    summary = pd.DataFrame([{
        "runs": int(len(df)),
        "solved_epochs": int(df["dcr_dominance_n"].sum()),
        "no_action_epochs": int(
            no_idle.fillna(0).sum()
            + zero_budget.fillna(0).sum()
            + no_route.fillna(0).sum()
        ),
        "hold_rate": float(
            (df["dcr_dominance_hold_rate"] * df["dcr_dominance_n"]).sum()
            / df["dcr_dominance_n"].sum()
        ),
        "mean_delta": float(
            (df["dcr_dominance_delta_mean"] * df["dcr_dominance_n"]).sum()
            / df["dcr_dominance_n"].sum()
        ),
        "mean_p95_delta": float(df["dcr_dominance_delta_p95"].mean()),
        "max_delta": float(df["dcr_dominance_delta_max"].max()),
        "mean_mixture_shortage": float(df["dcr_mixture_shortage_mean"].mean()),
        "mean_dcr_shortage_term": float(df["dcr_shortage_term_mean"].mean()),
    }])
    out_csv.parent.mkdir(parents=True, exist_ok=True)
    out_tex.parent.mkdir(parents=True, exist_ok=True)
    summary.to_csv(out_csv, index=False)

    row = summary.iloc[0]
    tex = (
        "% Auto-generated by scripts/analyze_path3_dcr_dominance.py\n\n"
        "\\begin{table}[t]\n"
        "\\centering\n"
        "\\caption{Empirical check of the DCR mixture-dominance condition. "
        "$\\Delta_{\\mathrm{mix}}\\le0$ is the condition under which the "
        "weighted DCR term upper-bounds retrieved-mixture shortage in "
        "\\Cref{thm:path3-dcr-certificate}. Values are computed on solved "
        "weighted-DCR repositioning epochs in the selected 8-scenario, 10-seed run.}\n"
        "\\label{tab:path3-dcr-dominance}\n"
        "\\small\n"
        "\\setlength{\\tabcolsep}{4pt}\n"
        "\\resizebox{\\linewidth}{!}{%\n"
        "\\begin{tabular}{@{}rrrrrrrr@{}}\n"
        "\\toprule\n"
        "Runs & Solved epochs & No-action epochs & Hold \\% & Mean $\\Delta_{\\mathrm{mix}}$ & "
        "Mean p95 $\\Delta_{\\mathrm{mix}}$ & Max $\\Delta_{\\mathrm{mix}}$ & "
        "Mean DCR / mixture \\\\\n"
        "\\midrule\n"
        f"{int(row['runs'])} & {int(row['solved_epochs'])} & "
        f"{int(row['no_action_epochs'])} & "
        f"{_fmt(100.0 * row['hold_rate'], 1)} & "
        f"{_fmt(row['mean_delta'], 2)} & "
        f"{_fmt(row['mean_p95_delta'], 2)} & "
        f"{_fmt(row['max_delta'], 2)} & "
        f"{_fmt(row['mean_dcr_shortage_term'], 1)} / "
        f"{_fmt(row['mean_mixture_shortage'], 1)} \\\\\n"
        "\\bottomrule\n"
        "\\end{tabular}%\n"
        "}\n"
        "\\end{table}\n"
    )
    out_tex.write_text(tex)
    return summary


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--results-csv",
        type=Path,
        default=Path("results/path3_dcr_dominance/external_baselines.csv"),
    )
    parser.add_argument(
        "--out-csv",
        type=Path,
        default=Path("results/path3_dcr_dominance/dcr_dominance_summary.csv"),
    )
    parser.add_argument(
        "--out-tex",
        type=Path,
        default=Path("paper/path3_dcr_dominance.tex"),
    )
    args = parser.parse_args()
    summary = build_table(args.results_csv, args.out_csv, args.out_tex)
    print(summary.to_string(index=False))
    print(f"\nWrote {args.out_csv}")
    print(f"Wrote {args.out_tex}")


if __name__ == "__main__":
    main()
