#!/usr/bin/env python3
"""Paired statistical diagnostics for the Path 3 TR-B table."""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import wilcoxon

RESULT_DIR = Path("results/path3_buffer70_m4_10seed")
OUT_DIR = Path("results/path3_paired_tests")
OUT_TEX = Path("paper/path3_paired_tests.tex")
OUT_MD = Path("docs/path3-paired-tests.md")
DCR = "spatial_gate_robust_cvar"


BASELINES = [
    ("scenario_chance_mpc", "Scenario chance-MPC"),
    ("share_lp_hand_tuned", "Share-target LP"),
    ("gpr_chance_mpc_lite", "GPR chance-MPC-lite"),
    ("wen2017_rebalancing", "Wen-style rebalancing"),
]

METRICS = {
    "mean_wait_s": "Wait",
    "reposition_dist_m_per_trip": "Repos.",
    "zone_wait_p90_p10_gap_s": "Zone gap",
}


def _fmt(x: float, digits: int = 2) -> str:
    if not np.isfinite(x):
        return "--"
    return f"{float(x):.{digits}f}"


def _p(x: float) -> str:
    if not np.isfinite(x):
        return "--"
    if x < 0.001:
        return "$<$0.001"
    return f"{x:.3f}"


def _paired_ci(
    values: np.ndarray,
    rng: np.random.Generator,
    n_boot: int = 10000,
) -> tuple[float, float]:
    values = np.asarray(values, dtype=float)
    if values.size == 0:
        return np.nan, np.nan
    idx = rng.integers(0, values.size, size=(n_boot, values.size))
    means = values[idx].mean(axis=1)
    return tuple(np.percentile(means, [2.5, 97.5]).tolist())


def _wilcoxon(values: np.ndarray) -> float:
    values = np.asarray(values, dtype=float)
    values = values[np.abs(values) > 1e-12]
    if values.size == 0:
        return np.nan
    return float(wilcoxon(values, alternative="two-sided").pvalue)


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    df = pd.read_csv(RESULT_DIR / "external_baselines.csv")
    keys = ["scenario", "seed"]
    dcr = df[df["method"] == DCR].set_index(keys)
    rng = np.random.default_rng(20260520)

    rows = []
    for method, label in BASELINES:
        base = df[df["method"] == method].set_index(keys)
        joined = dcr.join(base, lsuffix="_dcr", rsuffix="_base", how="inner")
        row: dict[str, float | str | int] = {
            "baseline": label,
            "method": method,
            "n": int(len(joined)),
        }
        for metric in METRICS:
            diff = (
                joined[f"{metric}_dcr"].to_numpy(dtype=float)
                - joined[f"{metric}_base"].to_numpy(dtype=float)
            )
            lo, hi = _paired_ci(diff, rng)
            row[f"{metric}_diff_mean"] = float(diff.mean())
            row[f"{metric}_ci_lo"] = lo
            row[f"{metric}_ci_hi"] = hi
            row[f"{metric}_p"] = _wilcoxon(diff)
        base_repos = joined["reposition_dist_m_per_trip_base"].to_numpy(dtype=float)
        dcr_repos = joined["reposition_dist_m_per_trip_dcr"].to_numpy(dtype=float)
        row["repos_reduction_pct"] = (
            (float(base_repos.mean()) - float(dcr_repos.mean()))
            / max(float(base_repos.mean()), 1e-12)
            * 100.0
        )
        rows.append(row)

    out = pd.DataFrame(rows)
    out.to_csv(OUT_DIR / "paired_tests.csv", index=False)

    tex_rows = []
    for _, row in out.iterrows():
        tex_rows.append(
            f"{row['baseline']} & {int(row['n'])} & "
            f"{_fmt(row['mean_wait_s_diff_mean'], 2)} "
            f"[{_fmt(row['mean_wait_s_ci_lo'], 2)}, {_fmt(row['mean_wait_s_ci_hi'], 2)}] & "
            f"{_fmt(row['repos_reduction_pct'], 1)} & "
            f"{_p(row['reposition_dist_m_per_trip_p'])} & "
            f"{_fmt(row['zone_wait_p90_p10_gap_s_diff_mean'], 2)} "
            f"[{_fmt(row['zone_wait_p90_p10_gap_s_ci_lo'], 2)}, "
            f"{_fmt(row['zone_wait_p90_p10_gap_s_ci_hi'], 2)}] \\\\"
        )

    tex = (
        "% Auto-generated by scripts/analyze_path3_paired_tests.py\n\n"
        "\\begin{table}[t]\n"
        "\\centering\n"
        "\\caption{Paired comparison of calibrated DCR against non-oracle "
        "baselines over matched scenario--seed runs. Wait and zone-gap columns "
        "report DCR minus baseline with bootstrap 95\\% confidence intervals; "
        "positive wait means DCR is slower. Repositioning reports percent "
        "reduction in empty meters per completed trip, with a paired Wilcoxon "
        "test on the raw meter difference.}\n"
        "\\label{tab:path3-paired-tests}\n"
        "\\small\n"
        "\\setlength{\\tabcolsep}{3pt}\n"
        "\\resizebox{\\linewidth}{!}{%\n"
        "\\begin{tabular}{lrrrrr}\n"
        "\\toprule\n"
        "Baseline & $n$ & $\\Delta$ wait (s) & Repos. red. \\% & "
        "$p$ repos. & $\\Delta$ zone gap (s) \\\\\n"
        "\\midrule\n"
        + "\n".join(tex_rows)
        + "\n\\bottomrule\n"
        "\\end{tabular}%\n"
        "}\n"
        "\\end{table}\n"
    )
    OUT_TEX.write_text(tex)

    lines = [
        "# Path 3 Paired Tests",
        "",
        "Paired over scenario and seed. Differences are DCR minus baseline.",
        "",
        "| Baseline | n | Delta wait | Repos reduction % | p repos | Delta zone gap |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for _, row in out.iterrows():
        lines.append(
            f"| {row['baseline']} | {int(row['n'])} | "
            f"{_fmt(row['mean_wait_s_diff_mean'], 2)} "
            f"[{_fmt(row['mean_wait_s_ci_lo'], 2)}, {_fmt(row['mean_wait_s_ci_hi'], 2)}] | "
            f"{_fmt(row['repos_reduction_pct'], 1)} | "
            f"{_p(row['reposition_dist_m_per_trip_p'])} | "
            f"{_fmt(row['zone_wait_p90_p10_gap_s_diff_mean'], 2)} "
            f"[{_fmt(row['zone_wait_p90_p10_gap_s_ci_lo'], 2)}, "
            f"{_fmt(row['zone_wait_p90_p10_gap_s_ci_hi'], 2)}] |"
        )
    OUT_MD.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT_DIR / 'paired_tests.csv'}")
    print(f"Wrote {OUT_TEX}")
    print(f"Wrote {OUT_MD}")
    print(out.to_string(index=False))


if __name__ == "__main__":
    main()
