#!/usr/bin/env python3
"""Aggregate calibrated constrained-DCR sweep outputs."""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

BASE_OUT = Path("results/path3_constrained_dcr_buffer70_sweep")
SELECTED_10SEED = Path("results/path3_buffer70_m4_10seed/external_baselines_summary.csv")
OUT_CSV = BASE_OUT / "constrained_dcr_sweep_summary.csv"
OUT_TEX = Path("paper/path3_constrained_dcr_sweep.tex")
OUT_MD = Path("docs/path3-constrained-dcr-sweep.md")


def _fmt(x: float, digits: int = 1) -> str:
    return f"{float(x):.{digits}f}"


def _load_status_counts(raw: pd.DataFrame) -> dict[str, int]:
    counts: dict[str, int] = {}
    if "solve_status_counts_json" not in raw.columns:
        return counts
    for payload in raw["solve_status_counts_json"].dropna():
        if not isinstance(payload, str) or not payload.strip():
            continue
        for key, value in json.loads(payload).items():
            counts[key] = counts.get(key, 0) + int(value)
    return counts


def _reduction_from_dir(path: Path) -> float:
    return float(path.name.replace("red_", "")) / 100.0


def _build_summary() -> pd.DataFrame:
    rows = []
    for run_dir in sorted(BASE_OUT.glob("red_*")):
        summary_path = run_dir / "external_baselines_summary.csv"
        raw_path = run_dir / "external_baselines.csv"
        if not summary_path.exists() or not raw_path.exists():
            continue
        summary = pd.read_csv(summary_path).iloc[0]
        raw = pd.read_csv(raw_path)
        status_counts = _load_status_counts(raw)
        total_status = sum(status_counts.values()) or 1
        success = status_counts.get("success_with_moves", 0)
        zero_round = status_counts.get("success_zero_rounded_moves", 0)
        no_idle = status_counts.get("no_idle_supply", 0)
        linprog_fail = sum(v for k, v in status_counts.items() if k.startswith("linprog_"))

        baseline_cvar = raw.get("dcr_baseline_cvar_mean", pd.Series([0.0]))
        cvar_budget = raw.get("dcr_cvar_budget_mean", pd.Series([0.0]))
        rows.append({
            "shortage_reduction": _reduction_from_dir(run_dir),
            "mean_wait_s": float(summary["mean_wait_s"]),
            "reposition_dist_m_per_trip": float(summary["reposition_dist_m_per_trip"]),
            "zone_wait_p90_p10_gap_s": float(summary["zone_wait_p90_p10_gap_s"]),
            "zone_wait_gini": float(summary["zone_wait_gini"]),
            "completion_rate": float(summary["completion_rate"]),
            "lp_solve_time_p95_ms": float(summary["lp_solve_time_p95_ms"]),
            "dcr_baseline_cvar_mean": float(baseline_cvar.mean()),
            "dcr_cvar_budget_mean": float(cvar_budget.mean()),
            "success_with_moves": success,
            "success_zero_rounded_moves": zero_round,
            "no_idle_supply": no_idle,
            "linprog_failures": linprog_fail,
            "success_rate": success / total_status,
            "status_counts_json": json.dumps(status_counts, sort_keys=True),
            "n": int(summary["n"]),
        })
    return pd.DataFrame(rows).sort_values("shortage_reduction")


def _selected_dcr() -> pd.Series:
    return pd.read_csv(SELECTED_10SEED).set_index("method").loc["spatial_gate_robust_cvar"]


def _write_tex(df: pd.DataFrame) -> None:
    rows = []
    for _, row in df.iterrows():
        rows.append(
            f"{_fmt(row['shortage_reduction'], 2)} & "
            f"{_fmt(row['mean_wait_s'], 1)} & "
            f"{_fmt(row['reposition_dist_m_per_trip'], 1)} & "
            f"{_fmt(row['zone_wait_p90_p10_gap_s'], 1)} & "
            f"{_fmt(row['zone_wait_gini'], 3)} & "
            f"{_fmt(row['success_rate'] * 100.0, 1)} \\\\"
        )
    tex = (
        "% Auto-generated by scripts/analyze_path3_constrained_dcr_sweep.py\n\n"
        "\\begin{table}[t]\n"
        "\\centering\n"
        "\\caption{Calibrated constrained-DCR sweep with 0.70 residual buffer. "
        "Success is the share of reposition epochs that solved and rounded to "
        "at least one empty movement.}\n"
        "\\label{tab:path3-constrained-sweep}\n"
        "\\small\n"
        "\\setlength{\\tabcolsep}{4pt}\n"
        "\\begin{tabular}{rrrrrr}\n"
        "\\toprule\n"
        "Reduction & Wait (s) & Repos. m/trip & Zone gap (s) & Zone Gini & Success \\% \\\\\n"
        "\\midrule\n"
        + "\n".join(rows)
        + "\n\\bottomrule\n"
        "\\end{tabular}\n"
        "\\end{table}\n"
    )
    OUT_TEX.write_text(tex)


def _write_md(df: pd.DataFrame) -> None:
    selected = _selected_dcr()
    best_wait = df.loc[df["mean_wait_s"].idxmin()]
    best_repos = df.loc[df["reposition_dist_m_per_trip"].idxmin()]
    selected_wait = float(selected["mean_wait_s"])
    selected_repos = float(selected["reposition_dist_m_per_trip"])
    promote = (
        float(best_wait["mean_wait_s"]) <= selected_wait + 1.5
        and float(best_wait["reposition_dist_m_per_trip"]) < selected_repos
    )
    verdict = (
        "Promote constrained DCR candidate for a 10-seed confirmation."
        if promote
        else (
            "Keep weighted DCR as headline; constrained DCR remains a supporting "
            "certificate/frontier formulation."
        )
    )

    lines = [
        "# Calibrated Constrained-DCR Sweep",
        "",
        "Generated by `scripts/analyze_path3_constrained_dcr_sweep.py`.",
        "",
        f"Selected weighted/calibrated DCR reference: {_fmt(selected_wait, 1)}s wait, "
        f"{_fmt(selected_repos, 1)}m/trip repositioning.",
        "",
        f"Best constrained wait point: reduction {_fmt(best_wait['shortage_reduction'], 2)}, "
        f"{_fmt(best_wait['mean_wait_s'], 1)}s wait, "
        f"{_fmt(best_wait['reposition_dist_m_per_trip'], 1)}m/trip.",
        "Lowest constrained movement point: reduction "
        f"{_fmt(best_repos['shortage_reduction'], 2)}, "
        f"{_fmt(best_repos['mean_wait_s'], 1)}s wait, "
        f"{_fmt(best_repos['reposition_dist_m_per_trip'], 1)}m/trip.",
        "",
        f"Verdict: {verdict}",
        "",
        "| Reduction | Wait | Repos. m/trip | Zone gap | Zone Gini | Success % | Status counts |",
        "|---:|---:|---:|---:|---:|---:|---|",
    ]
    for _, row in df.iterrows():
        lines.append(
            f"| {_fmt(row['shortage_reduction'], 2)} | "
            f"{_fmt(row['mean_wait_s'], 1)} | "
            f"{_fmt(row['reposition_dist_m_per_trip'], 1)} | "
            f"{_fmt(row['zone_wait_p90_p10_gap_s'], 1)} | "
            f"{_fmt(row['zone_wait_gini'], 3)} | "
            f"{_fmt(row['success_rate'] * 100.0, 1)} | "
            f"`{row['status_counts_json']}` |"
        )
    OUT_MD.write_text("\n".join(lines) + "\n")


def main() -> None:
    df = _build_summary()
    if df.empty:
        raise SystemExit(f"No completed sweep runs found under {BASE_OUT}")
    BASE_OUT.mkdir(parents=True, exist_ok=True)
    df.to_csv(OUT_CSV, index=False)
    _write_tex(df)
    _write_md(df)
    print(f"Wrote {OUT_CSV}")
    print(f"Wrote {OUT_TEX}")
    print(f"Wrote {OUT_MD}")


if __name__ == "__main__":
    main()
