#!/usr/bin/env python3
"""Build compact Path 3 paper tables from cached results."""

from __future__ import annotations

from pathlib import Path

import pandas as pd

RESULT_DIR = Path("results/path3_buffer70_m4_10seed")
BUFFER_DIR = Path("results/path3_retrieval_buffers_top5")
OUT = Path("paper/path3_results_tables.tex")


def _fmt(x: float, digits: int = 1) -> str:
    return f"{float(x):.{digits}f}"


def main() -> None:
    summary = pd.read_csv(RESULT_DIR / "external_baselines_summary.csv")
    buffer_summary = pd.read_csv(BUFFER_DIR / "buffer_summary.csv")
    coverage = pd.read_csv(BUFFER_DIR / "heldout_buffer_validation_summary.csv")

    methods = [
        ("oracle_mpc", "Oracle MPC"),
        ("scenario_chance_mpc", "Scenario chance-MPC"),
        ("share_lp_hand_tuned", "Share-target LP"),
        ("spatial_gate_robust_cvar", "Calibrated DCR"),
        ("gpr_chance_mpc_lite", "GPR chance-MPC-lite"),
        ("wen2017_rebalancing", "Wen-style rebalancing"),
        ("batch_replay", "Batch replay"),
    ]
    lookup = summary.set_index("method")
    rows = []
    for key, label in methods:
        r = lookup.loc[key]
        improvement = (
            "--"
            if pd.isna(r.get("improvement_vs_replay_pct"))
            else _fmt(r["improvement_vs_replay_pct"], 1)
        )
        rows.append(
            f"{label} & {_fmt(r['mean_wait_s'], 1)} & "
            f"{_fmt(r['reposition_dist_m_per_trip'], 1)} & "
            f"{_fmt(r['zone_wait_p90_p10_gap_s'], 1)} & "
            f"{_fmt(r['zone_wait_gini'], 3)} & {improvement} \\\\"
        )

    table1 = r"""\begin{table}[t]
\centering
\caption{Replay-demand controller comparison over 8 scenarios and 10 seeds.}
\label{tab:path3-main}
\small
\setlength{\tabcolsep}{3pt}
\resizebox{\linewidth}{!}{%
\begin{tabular}{@{}p{0.30\linewidth}rrrrr@{}}
\toprule
Method & Wait (s) & Repos. m/trip & Zone gap (s) & Zone Gini & Improv. \% \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
}
\end{table}
"""

    buf_lookup = buffer_summary.set_index("alpha")
    cov_lookup = coverage.set_index("alpha")
    buffer_rows = []
    for alpha in ["0.70", "0.80", "0.90", "0.95"]:
        alpha_value = float(alpha)
        if alpha_value in buf_lookup.index:
            b = buf_lookup.loc[alpha_value]
        else:
            b = buf_lookup.loc[alpha]
        if alpha_value in cov_lookup.index:
            c = cov_lookup.loc[alpha_value]
        else:
            c = cov_lookup.loc[alpha]
        buffer_rows.append(
            f"{alpha} & {_fmt(b['zone_buffer_mass'], 3)} & "
            f"{_fmt(b['positive_mass_quantile'], 3)} & "
            f"{_fmt(c['positive_mass_coverage'] * 100.0, 1)} & "
            f"{_fmt(c['max_zone_coverage'] * 100.0, 1)} & "
            f"{_fmt(c['zonewise_coverage'] * 100.0, 1)} \\\\"
        )

    table2 = r"""\begin{table}[t]
\centering
\caption{Retrieval residual calibration and held-out coverage. Coverage is measured
on 104 leakage-held-out blocks. Full-zone coverage requires simultaneous coverage
of every zone and is reported only as a diagnostic.}
\label{tab:path3-coverage}
\small
\setlength{\tabcolsep}{3pt}
\resizebox{\linewidth}{!}{%
\begin{tabular}{@{}p{0.18\linewidth}rrrrr@{}}
\toprule
Buffer alpha & Buffer mass & Pos. mass q & Pos. mass cov. & Max-zone cov. & Full-zone cov. \\
\midrule
""" + "\n".join(buffer_rows) + r"""
\bottomrule
\end{tabular}
}
\end{table}
"""

    OUT.write_text("% Auto-generated by scripts/build_path3_tables.py\n\n" + table1 + "\n" + table2)
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
