#!/usr/bin/env python3
"""Run focused Path 3 fleet-size sensitivity for DCR comparators."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from types import SimpleNamespace

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from scripts.external_baselines_eval import evaluate

METHODS = [
    "share_lp_hand_tuned",
    "scenario_chance_mpc",
    "spatial_gate_robust_cvar",
]
METHOD_LABELS = {
    "share_lp_hand_tuned": "Share-target LP",
    "scenario_chance_mpc": "Scenario chance-MPC",
    "spatial_gate_robust_cvar": "Calibrated DCR",
}


def _fmt(value: float, digits: int = 1) -> str:
    return f"{float(value):.{digits}f}"


def _args_for_ratio(args: argparse.Namespace, ratio: float) -> SimpleNamespace:
    return SimpleNamespace(
        gate=args.gate,
        out_dir=str(args.out_dir),
        seeds=args.seeds,
        scenarios=args.scenarios,
        top_k=args.top_k,
        fleet_ratio=ratio,
        min_fleet=args.min_fleet,
        policy_h3_res=args.policy_h3_res,
        oracle_lookahead=15.0,
        share_move_fraction=args.share_move_fraction,
        wen_move_fraction=0.30,
        oracle_move_fraction=0.50,
        chance_lookahead=15.0,
        chance_quantile=args.chance_quantile,
        chance_risk_weight=args.chance_risk_weight,
        chance_move_fraction=args.chance_move_fraction,
        gpr_chance_lookahead=15.0,
        gpr_chance_quantile=0.90,
        gpr_chance_risk_weight=0.80,
        gpr_chance_move_fraction=0.50,
        robust_lookahead=15.0,
        robust_alpha=args.robust_alpha,
        robust_risk_weight=args.robust_risk_weight,
        robust_mean_weight=args.robust_mean_weight,
        robust_move_cost_multiplier=args.robust_move_cost_multiplier,
        robust_shortage_reduction=0.25,
        robust_mean_slack_weight=1e-3,
        robust_buffer_json=args.robust_buffer_json,
        robust_buffer_alpha=args.robust_buffer_alpha,
        robust_move_fraction=args.robust_move_fraction,
        raw_lp_move_fraction=0.50,
        dqn_move_fraction=0.25,
        reposition_interval_steps=args.reposition_interval_steps,
        dqn_checkpoint=None,
        router=args.router,
        osrm_grid_size=args.osrm_grid_size,
        methods=",".join(METHODS),
        router_actual=args.router,
    )


def _summarize(df: pd.DataFrame) -> pd.DataFrame:
    summary = (
        df.groupby(["fleet_ratio", "method"], as_index=False)
        .agg(
            wait_s=("mean_wait_s", "mean"),
            repos_m_per_trip=("reposition_dist_m_per_trip", "mean"),
            zone_gap_s=("zone_wait_p90_p10_gap_s", "mean"),
            zone_gini=("zone_wait_gini", "mean"),
            completion=("completion_rate", "mean"),
            n=("mean_wait_s", "size"),
        )
    )
    dcr = summary[summary["method"] == "spatial_gate_robust_cvar"][
        ["fleet_ratio", "wait_s", "repos_m_per_trip"]
    ].rename(columns={"wait_s": "dcr_wait_s", "repos_m_per_trip": "dcr_repos_m_per_trip"})
    base_rows = summary[summary["method"].isin(["share_lp_hand_tuned", "scenario_chance_mpc"])]
    comp = base_rows.merge(dcr, on="fleet_ratio", how="left")
    comp["dcr_wait_penalty_s"] = comp["dcr_wait_s"] - comp["wait_s"]
    comp["dcr_saved_m_per_trip"] = comp["repos_m_per_trip"] - comp["dcr_repos_m_per_trip"]
    comp["dcr_saved_pct"] = 100.0 * comp["dcr_saved_m_per_trip"] / comp["repos_m_per_trip"]
    return summary, comp


def _write_tex(comp: pd.DataFrame, out_tex: Path) -> None:
    lines = []
    for ratio in sorted(comp["fleet_ratio"].unique()):
        view = comp[comp["fleet_ratio"] == ratio].set_index("method")
        share = view.loc["share_lp_hand_tuned"]
        chance = view.loc["scenario_chance_mpc"]
        lines.append(
            f"{_fmt(ratio, 2)} & "
            f"{_fmt(share['dcr_wait_penalty_s'], 2)} & "
            f"{_fmt(share['dcr_saved_pct'], 1)} & "
            f"{_fmt(chance['dcr_wait_penalty_s'], 2)} & "
            f"{_fmt(chance['dcr_saved_pct'], 1)} \\\\"
        )
    tex = (
        "% Auto-generated by scripts/run_path3_fleet_sensitivity.py\n\n"
        "\\begin{table}[t]\n"
        "\\centering\n"
        "\\caption{Fleet-size sensitivity for the calibrated DCR frontier. "
        "Entries compare DCR with the two strongest non-oracle wait baselines "
        "at the same fleet ratio; positive wait penalty means DCR is slower, "
        "and saved \\% is the reduction in empty meters per completed trip.}\n"
        "\\label{tab:path3-fleet-sensitivity}\n"
        "\\small\n"
        "\\setlength{\\tabcolsep}{4pt}\n"
        "\\resizebox{\\linewidth}{!}{%\n"
        "\\begin{tabular}{@{}rrrrr@{}}\n"
        "\\toprule\n"
        "Fleet ratio & Wait vs Share (s) & Saved vs Share \\% & "
        "Wait vs Chance (s) & Saved vs Chance \\% \\\\\n"
        "\\midrule\n"
        + "\n".join(lines)
        + "\n\\bottomrule\n"
        "\\end{tabular}%\n"
        "}\n"
        "\\end{table}\n"
    )
    out_tex.parent.mkdir(parents=True, exist_ok=True)
    out_tex.write_text(tex)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--gate", default="results/path2_gate_spatial/similarity_gate.pt")
    parser.add_argument("--out-dir", type=Path, default=Path("results/path3_fleet_sensitivity"))
    parser.add_argument("--out-tex", type=Path, default=Path("paper/path3_fleet_sensitivity.tex"))
    parser.add_argument("--scenarios", default="jan_weekday_am,jan_nye_pm,jun_late_night")
    parser.add_argument("--seeds", default="42,43,44")
    parser.add_argument("--fleet-ratios", default="0.12,0.15,0.18")
    parser.add_argument("--top-k", type=int, default=5)
    parser.add_argument("--min-fleet", type=int, default=50)
    parser.add_argument("--policy-h3-res", type=int, default=None)
    parser.add_argument("--share-move-fraction", type=float, default=0.50)
    parser.add_argument("--chance-quantile", type=float, default=0.80)
    parser.add_argument("--chance-risk-weight", type=float, default=0.70)
    parser.add_argument("--chance-move-fraction", type=float, default=0.50)
    parser.add_argument("--robust-alpha", type=float, default=0.80)
    parser.add_argument("--robust-risk-weight", type=float, default=1.0)
    parser.add_argument("--robust-mean-weight", type=float, default=0.25)
    parser.add_argument("--robust-move-cost-multiplier", type=float, default=4.0)
    parser.add_argument(
        "--robust-buffer-json",
        default="results/path3_retrieval_buffers_top5/buffers.json",
    )
    parser.add_argument("--robust-buffer-alpha", default="0.70")
    parser.add_argument("--robust-move-fraction", type=float, default=0.50)
    parser.add_argument("--reposition-interval-steps", type=int, default=6)
    parser.add_argument("--router", choices=("haversine", "osrm-grid", "osrm"), default="haversine")
    parser.add_argument("--osrm-grid-size", type=int, default=25)
    args = parser.parse_args()

    args.out_dir.mkdir(parents=True, exist_ok=True)
    frames = []
    ratios = [float(x.strip()) for x in args.fleet_ratios.split(",") if x.strip()]
    for ratio in ratios:
        print(f"\n=== Fleet ratio {ratio:.2f} ===")
        run_args = _args_for_ratio(args, ratio)
        frame = evaluate(run_args)
        frames.append(frame)

    full = pd.concat(frames, ignore_index=True)
    full.to_csv(args.out_dir / "fleet_sensitivity.csv", index=False)
    summary, comp = _summarize(full)
    summary.to_csv(args.out_dir / "fleet_sensitivity_summary.csv", index=False)
    comp.to_csv(args.out_dir / "fleet_sensitivity_comparison.csv", index=False)
    _write_tex(comp, args.out_tex)

    print("\nSummary:")
    print(summary.to_string(index=False))
    print("\nDCR comparisons:")
    print(comp.to_string(index=False))
    print(f"\nWrote {args.out_dir}")
    print(f"Wrote {args.out_tex}")


if __name__ == "__main__":
    main()
